### ISSUE TITLE
yaml templates using text/template and sprig

### ISSUE THREAD

**Issue by webframp** [dominikh/go-mode.el#415]
Hey there, 

Sorry for making an issue if this seems unrelated or has been answered, I searched around and have asked other places to no avail so far.

I deal quite a bit with yaml template files that have inline template syntax, based on [text/template](https://pkg.go.dev/text/template) and [sprig](https://pkg.go.dev/github.com/Masterminds/sprig/v3#section-readme), you can blame kubernetes.

Example snippet:

```yaml
{{- if .featureflag}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-operator
  name: app-operator
  namespace: app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-operator
  strategy:
    type: RollingUpdate
  template:
  ...
```

or another example:
```yaml
      containers:
      - name: coredns
        {{- if regexMatch "^1\\.2[34]$" .k8sversion }}
        image: coredns:v1.8.7
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi

```

I have yet to find a great mode configuration for working with these and am wondering what people who use go-mode are using, if they have this same scenario. 

What I've investigated:

First was of course [yaml-mode](https://github.com/yoshiki/yaml-mode) of course, which is the best I can get so far, but occasionally breaks on some template syntax. This is what I'm currently using by default.

Next I found https://github.com/dominikh/go-mode.el/issues/184 which was talking about go template syntax in web files, but web-mode specifically does not support yaml syntax and it seems it will not be added: https://github.com/fxbois/web-mode/issues/934

Third I was directed to [poly-ansible](https://gitlab.com/mavit/poly-ansible/-/tree/main) that uses [polymode](https://polymode.github.io/), which seems pretty promising but: 1) pulls in ansible-mode as a dependency and 2) is for jinja2 templates, which while similar are not quite the same as go templates.

Does anyone else using go-mode have this same problem? 

No offense if you choose to just close but thanks for any info that might help
